[project]
site_name = "copier-python"
site_description = "Copier template for Python projects with modern tooling"
site_author = "Stephen Kent"
site_url = "https://smkent.github.io/copier-python"
repo_url = "https://github.com/smkent/copier-python"
repo_name = "smkent/copier-python"
copyright = "&copy; 2026 Stephen Kent"

nav = [
  { "Home" = [
    { "Overview" = "index.md" },
    { "License" = "license.md" },
  ] },
  { "Development" = [
    { "Contributing" = "contributing.md" },
    { "Maintaining" = "maintaining.md" },
  ] },
]

# ----------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------
[project.theme]
language = "en"
features = [
    "content.code.annotate",
    "content.code.copy",
    "content.tooltips",
    "navigation.expand",
    "navigation.footer",
    "navigation.instant",
    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "search.highlight",
    "toc.follow",
]

[project.theme.icon]
logo = "lucide/package-plus"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "teal"
accent = "purple"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "lime"
toggle.icon = "material/weather-night"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/smkent"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/copier-python/"

# ----------------------------------------------------------------------------
# Markdown extensions
# ----------------------------------------------------------------------------
[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.def_list]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.highlight]

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.snippets]
base_path = ["."]
check_paths = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
